### ISSUE TITLE
Unhandled Rejection 'bluebird.js'

### ISSUE THREAD

**Issue by briandpassa** [foxhound87/rfx-stack#13]
Anyone have this warning when running the current repo? I didn't change anything in the source code.

Unhandled rejection [object Object](No stack trace)
From previous event:
    at authenticateSocket (eval at <anonymous> (http://localhost:3100/bundle.js:10160:2), <anonymous>:45:10)
From previous event:
    at _default (eval at <anonymous> (http://localhost:3100/bundle.js:2036:2), <anonymous>:26:20)
    at eval (eval at <anonymous> (http://localhost:3100/bundle.js:3080:2), <anonymous>:27:36)
    at Object.<anonymous> (http://localhost:3100/bundle.js:3080:2)
    at __webpack_require__ (http://localhost:3100/bundle.js:556:30)
    at fn (http://localhost:3100/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3100/bundle.js:589:19)
    at **webpack_require** (http://localhost:3100/bundle.js:556:30)
    at http://localhost:3100/bundle.js:579:37
    at http://localhost:3100/bundle.js:582:10

**Comment by foxhound87** [comment]
It seems need a `.catch()` on the `app().authenticate()` promise.
This error is related to feathers-authentication package, authenticateSocket is here:
https://github.com/feathersjs/feathers-authentication/blob/master/src/client/utils.js#L30
Are you able to login successfully?

And I need additional info, your node/npm version, and try to add `.catch((err) => console.log(err));` concatenating it after `.then()` of the `app().authenticate(...)` in the **AuthStore**. The error should be thrown in the `jwtAuth()` method if you are already logged, otherwise in the `login()` method.

Post here the console.log result, please.

**Comment by briandpassa** [comment]
Hi, yes I can register and login successfully.

I use npm version 3.8.6, node version v5.11.0.

Anyway, after I added that catch statement, there's no more such warning. Thanks!

The console.log is clean, except for the unrelated "checksum" warning which is referenced in another Open issue here.

**Comment by briandpassa** [comment]
But when I try to logout and login again, there is this warning in the console log:

"Invoking 'alert()' during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details."

**Comment by foxhound87** [comment]
Maybe that warning is thrown in your specific version of the browser, it's about the use of `alert()` function.
I used it only for demo purpose, it is called in the **AuthModal** component after a successful login/register event, and you should remove it.
Let me know if the waring vanish after removing that `alert()` function.

**Comment by briandpassa** [comment]
All alright now. Thanks for taking the time to answer my newbie questions! :D

**Comment by foxhound87** [comment]
You are welcome! thank you for your contribution!

**Comment by foxhound87** [comment]
@briandpassa I removed the alert() function with this commit introducing the use of the SnackBar: https://github.com/foxhound87/rfx-stack/commit/7f6d3213155b21826c58c25a61a1219f4d11c717
