### ISSUE TITLE
Live Linter now applicable on API files during development?

### ISSUE THREAD

**Issue by briandpassa** [foxhound87/rfx-stack#16]
It seems that the linter is not being applied on API files when development server is running. Only when we `build:server:api` that the linter is applied. 

Live Linter on other files are fine.

**Comment by foxhound87** [comment]
I can't reproduce your issue.

But I think you are confusing the live linter (the error shown on the editor) from the syntax checking happening in the building process (that you can see in the terminal).

On `npm run api:dev` ther's no build process and no live syntax checking (it's just 1-time checked when launching the command).

Instead `npm run web:dev` has live syntax checking because the code si built on each code change from webpack using hot-loader.

**Comment by briandpassa** [comment]
I see. I was wondering whether live syntax checking using webpack hot-loader can be done on api files too.

**Comment by foxhound87** [comment]
The hot reload for the node server is a cool features that will be nice to have. 
I already have it in my todo list!

**Comment by briandpassa** [comment]
Great! Will be waiting for it.

**Comment by foxhound87** [comment]
@briandpassa For now I installed nodemon to auto restart the api server. https://github.com/foxhound87/rfx-stack/commit/b6699a5b4372c47c21009db99f9a96ccd8bfd889

The server HMR it's a bit tricky to accomplish for now, expecially to integrate in the current webpack config but I will try.

**Comment by briandpassa** [comment]
Great! Thanks
