### ISSUE TITLE
Bluebird.js errors and HMR 

### ISSUE THREAD

**Issue by jonandrewdavis** [foxhound87/rfx-stack#26]
Enjoying using rfx-stack on a large project. Thank you for the work.

Was looking at some past issues, but they didn't really address my specific problem.

I am seeing this bluebird.js warning A LOT. to the point it's difficult to use the console. 

```
Warning: a promise was rejected with a non-error: [object String]
    at Manager.eval (eval at <anonymous> (http://localhost:3000/bundle.js:2084:2), <anonymous>:21:15)
    at Socket.eval (eval at <anonymous> (http://localhost:3000/bundle.js:2084:2), <anonymous>:21:15)
From previous event:
    at connected (eval at <anonymous> (http://localhost:3000/bundle.js:5294:2), <anonymous>:15:10)
From previous event:
    at Object.app.authenticate (eval at <anonymous> (http://localhost:3000/bundle.js:5288:2), <anonymous>:45:25)
    at Array.forEach (native)
    at rehydrate (eval at <anonymous> (http://localhost:3000/bundle.js:3974:2), <anonymous>:35:26)
```

I'm having a difficulty figuring out how to resolve these. They happen:
1. when I make changes and hot reload any `pure` or `stateless` component.  That includes `stateless functional components`. 
2. Doesn't seem to happen on components that are hooked up to a store via `connect` 

I looked up this:
http://bluebirdjs.com/docs/warning-explanations.html

But to resolve them, I'm not sure where I'd add errors or whatnot without line numbers or files. they're all `bundle.js` errors

Secondly, I noticed that, `config.client.js` if I remove: 

```
      new webpack.ProvidePlugin({
        Promise: 'bluebird',
        fetch: 'imports?this=>global!exports?global.fetch!whatwg-fetch',
      }),
```

It will stop the errors. What exactly is this doing? Is it overriding the normal Promise with a `bluebird.js` promise? What's the second line doing? My app seemed to work fine without it. 

How is bluebird helping? 

Sorry for a pretty unspecific issue. Looking for help around hydration. 

My basic question is: 
- How can I resolve these warnings? 
- How can I go about troubleshooting them? 
- Can I safely suppress them and go on with my life? How? 

Thanks!  Hope this isn't too annoying/vague. Thanks for your work.

**Comment by foxhound87** [comment]
Hi @jonandrewdavis 

thank you for using the RFX Stack!

I used `bluebird` as `polyfill` so `Promise` can work the same on every browser, whether do not support it or have a different version.

The `fetch` polyfill was moved to the entry point after `babel-polyfill` for both the client and server, fixed in this commit https://github.com/foxhound87/rfx-stack/commit/ff138bddab3d7a0cd0e76711bba9f558b1ec3b12

The `/utils/request.js` was removed too because incomplete and broken, I suggest to use something like `axios`, `superagent` or `request`.

The `Warning: a promise was rejected with a non-error` in your case is related to the `authenticate` promise and is an authentication failure, maybe you are trying to reconnect with a token that is not valid anymore. But I don't think it is related to the hot reload.

Anyway you should be able to see the full error message using `.catch()` on the `authenticate()` promise like so: https://github.com/foxhound87/rfx-stack/blob/ff138bddab3d7a0cd0e76711bba9f558b1ec3b12/src/shared/stores/auth.js#L30

Let me know if it helped!

**Comment by jonandrewdavis** [comment]
Yes, thank you! This was of great help. We are pretty far from the original fork, so i'll try to manually incorporate some changes from ff138bd to fix what we are seeing.
