### ISSUE TITLE
Authenticated routes

### ISSUE THREAD

**Issue by mishkinf** [foxhound87/rfx-stack#37]
The way that the app is structured with jwt tokens being used on the frontend provides a delay in fetching the user (occurring asynchronously). How does one create a way to ensure the user is logged in and if not redirects them away from certain routes? It might be a good issue to tackle in this project and also to provide an example in the application of a page that can only be accessed if you're authenticated.

**Comment by foxhound87** [comment]
You can find an example of the rfx-stack with authenticated routes on this repo: 

https://bitbucket.org/foxhound87/rfx-stack-ssr-test/branch/ssr-cookie

In the ssr-cookie branch you can see an implementation of the cookie which handle the jwt token on the ssr server for the isomorphic authentication.

I have not yet updated the github repo because I'm testing it with the updated version of feathers.

I will update it asap, in the meanwhile take a look there.

**Comment by mishkinf** [comment]
Thats awesome! Yeah, I was messing around with my own implementation of passing a cookie to the server as a solution but I figured I would pose it as an issue as it will be 100% necessary. Great project. Thank you!

**Comment by foxhound87** [comment]
The only thing that does not convince me of the rfx-stack is react-router.

I was wondering if would be better to replace it for another approach more suitable for MobX, something like explained in [this blog](https://medium.com/@mweststrate/how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount-cc90b787aa37) by Michel Weststrate.

**Comment by foxhound87** [comment]
The repo is now updated.
