### ISSUE TITLE
Adding facebook/google auth

### ISSUE THREAD

**Issue by 29er** [foxhound87/rfx-stack#4]
@foxhound87 I noticed that you may have had the same issues as me trying to integrate auth for facebook/google etc.  I am having trouble getting those to work. is there a reason why to don't consider auth a 'service' in your app ?  
You obviously have more experience with the feathers framework as I am basically going through the 'starter' examples where the auth is a service....
thanks for any insight.

**Comment by foxhound87** [comment]
I haven't tried to integrate the auth plugins yet, I have to finish what's commented there in the auth.js.
I still don't know what to do with the auth.js, I put it outside of the services directory because the "regular" services are auto-loaded automatically and I don't know if it behave like them. 
I'm exploring feathers too because it's almost new on the scene.
Now I just pushed an update with a new auth store to deal with the feathers auth, but I have to fix the authenticate method on the production env. It works only for the dev env for now.

**Comment by 29er** [comment]
thanks! @foxhound87
