### ISSUE TITLE
A newbie's question

### ISSUE THREAD

**Issue by littlepoolshark** [foxhound87/rfx-stack#46]
I am learning mobx by using your react-mobx-react-router4-boilerplate。But i can not understand the purpose of rfx-core package during reading the source code.Could you give me some directions of  understanding  rfx-core?

**Comment by foxhound87** [comment]
Hi @littlepoolshark 

the **react-router** version used by the RFX-Stack is 3 (not 4).

The **rfx-core** package is a collection of utilities and advanced functionalities for the **State Hydration** of **SSR** (Server Side Rendering) which will work with mobx + react-router v3 out of the box. This can eventually be used to enable SSR also on others boilerplates which use those packages. 

The main purpose of the package is to provide a clean API to sync the client state with the server state of the app because the app is initially rendered on the server side, the client side will only start to work only on the first user input (or if designed programmatically). The package initializes the stores and renders the page on the server side on each router request, then the state is passed to the client through the state hydration mechanism and re-injected into the stores. In other words, the client will start to work with the state provided by the server. You also gain a super rendering speed and indexing by search engines.

In the **rfx-core** [documentation](https://github.com/foxhound87/rfx-core/blob/master/DOCUMENTATION.md) you can find some utilities to deal with the stores initialization and the state hydration (some examples are also provided by links to the RFX-Stack code).

You can find all info you need about the logic behind the **stores initialization** and the **state hydration** (which is implemented in the **rfx-core** package) on this blog post: [State Management & Hydration with MobX](https://medium.com/@foxhound87/state-management-hydration-with-mobx-we-must-react-ep-05-1922a72453c6) (there are also previous posts which can help you to connect the dots).

**Comment by littlepoolshark** [comment]
@foxhound87 
Thank you so much for patien explaination.I am  quite understand the rfx-core package after following your guide.Thanks again!
